### ISSUE TITLE
1.0r6?

### ISSUE THREAD

**Issue by larsenglund** [sumotoy/TFT_ILI9163C#29]
It's monday now... ;)
Thanks for your awesome work with this library!

**Comment by sumotoy** [comment]
I'm currently tuning color parameters, each display's have different settings, so I definetively release today.
It's a big update, structure changed a lot, all SPI calls are unified and separate between processors and now it's far more easy adapt different (future) display's since each one has it's own file.

**Comment by larsenglund** [comment]
Awesome, looking forward to trying it out!

**Comment by sumotoy** [comment]
Since I had to fix the issue of preprocessor placeholder, had to change font scheme. This forced me to recompile all font as well and have to create a new font conversion template, new preset, and modify the documentation as well. I don't have here any 8bit CPU (like uno) or DUE so I sent beta code to 2 betatester to check if everithing run as it should, for now Teensy's works and ESP8266 work, tested with all the RED pcb display's. 
I'm actually tuning some color parameters for both display and try to shrink a bit the library code to fit with UNO's or tiny memory CPU, I have already get 15% less but I'm try to shrink other 22%.
This is why I'm late with this, big changes, but library it's so popular that changes should be transparent or many projects have to be changed.

Preview of the 1.0r6 released, has some glitches on INIT parameters but this take time to fix and I will release a better version when I have some spare time, these chinese never give any info about the TFT and the last yello pin one has no info at all.
